@startuml
skin rose

'code   void SilverController::pairing_phone() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::blue_led_off() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::white_led_off() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::blue_led_blinking() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::white_led_glow() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::blue_led_constant_glow() { LOGD("[ACTION %s]\n", __func__); }
'code   void SilverController::launch_home_screen() { LOGD("[ACTION %s]\n", __func__); }

[*] --> VehiculeOff

VehiculeOff --> BluetoothDiscoverable : ignition on acc on
VehiculeOff <-- BluetoothDiscoverable : ignition off acc off
VehiculeOff <-- BluetoothDisconnected : ignition off acc off

BluetoothDiscoverable --> BluetoothConnected : pairing successful
BluetoothDiscoverable <-- BluetoothConnected : long SPS press /  pairing_phone()
' BluetoothDiscoverable --> BluetoothDisconnected : bluetooth failure [ pairing unsuccessful || auto connection failure || 120s lapse ]
BluetoothDiscoverable --> BluetoothDisconnected : bluetooth failure
BluetoothDiscoverable <-- BluetoothDisconnected : long SPS press / pairing_phone()

BluetoothConnected --> BluetoothDisconnected : phone bluetooth disconnected


VehiculeOff : comment / Not available for pairing bluetooth
VehiculeOff : entry / blue_led_off(); white_led_off()
BluetoothDiscoverable : comment / Avaialble for pairing or automatic connection or manual connection
BluetoothDiscoverable : entry / blue_led_blinking()
BluetoothConnected : comment / Connected to phone via bluetooth
BluetoothConnected : entry / blue_led_constant_glow()
BluetoothConnected : on short SPS press / launch_home_screen()
BluetoothDisconnected : comment / No bluetooth connected
BluetoothDisconnected : entry / white_led_glow()

@enduml
