@startuml
skin rose

'[brief] State2 has an event to transit to State1 but has no event and no guard for State3.
'[brief] Therefore the state machine is not determinist.

[*] -> State1
State1 --> State2
State2 --> State1 : event
State2 -> State3

@enduml
