@startuml
skin rose

'[header]  #  define Disable false
'[header]  #  define Enable true

'[code] private:
'[code]    bool LED_LKS;
'[code]    bool LED_lane;
'[code]    bool LED_steering;
'[code]    bool servoing;

'[init]    LED_LKS = LED_lane = LED_steering = servoing = Disable;

[*] --> LKSModeOff

LKSModeOff : comment / Line Keep System OFF
LKSModeOn : comment / Line Keep System ON
WaitDetect : comment / LKS is not detecting the lane
DetectLane : comment / LKS is detecting crossing the lane
FollowLane : comment / LKS is following the lane

LKSModeOff --> LKSModeOn : btn_LKS\n--\nLED_LKS = Enable
LKSModeOn --> LKSModeOff : btn_LKS\n--\nLED_LKS = Disable
LKSModeOn -> DetectLane : detect\n--\nLED_lane = Enable

DetectLane --> LKSModeOff : btn_LKS\n--\nLED_LKS = Disable;\nLED_lane = Disable
DetectLane -> WaitDetect : not detect\n--\nLED_lane = Disable
DetectLane --> FollowLane : set\n--\nLED_steering = Enable;\nservoing = Enable

FollowLane --> WaitDetect : not detect\n--\nLED_lane = Disable;\nLED_steering = Disable;\nservoing = Disable
FollowLane -> LKSModeOff : btn_LKS\n--\nLED_LKS = Disable;\nLED_lane = Disable;\nLED_steering = Disable;\nservoing = Disable
FollowLane -> DetectLane : cancel\n--\nLED_steering = Disable;\nservoing = Disable

WaitDetect -> DetectLane : detect\n--\nLED_lane = Enable
WaitDetect -> LKSModeOff : btn_LKS\n--\nLED_LKS = Disable

@enduml
