@startuml
skin rose

Idle : entry / printf("Motor is hlated\\n")
Idle : exit / printf("Motor is started\\n")
[*] --> Idle
Idle --> Start : setSpeed(refSpeed) [ refSpeed > 0 ]
Start --> Stop : halt
Start -> Spinning : setSpeed(refSpeed) [ refSpeed > 0 ]
Stop <- Spinning : halt
' FIXME not managed: double transition
' Stop <- Spinning : setSpeed(refSpeed) [ refSpeed == 0 ]
' Stop <- Spinning : halt
Idle <- Stop

Spinning : on setSpeed(refSpeed) [ refSpeed >= 0 ]

@enduml
