@startuml
skin rose

'[brief] Test simple composite state.

[*] -> EnableSystem

state EnableSystem {
  [*] -> ON
  ON -> OFF : off
  OFF -> ON : on
}

EnableSystem -> DisableSystem : disable
EnableSystem <- DisableSystem : enable

@enduml
