@startuml
skin rose

'[brief] Test simple orthogonal state.

[*] -> EnableSystem

state EnableSystem {
  [*] -> State1
  State1 -> [*]

--

  [*] -> State2
  State2 -> [*]
}

EnableSystem -> DisableSystem

@enduml
